// Code generated by MockGen. DO NOT EDIT.
// Source: tests/case4/kod_gen_interface.go
//
// Generated by this command:
//
//	mockgen -source tests/case4/kod_gen_interface.go -destination tests/case4/kod_gen_mock.go -package case4
//

// Package case4 is a generated GoMock package.
package case4

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTest1Component is a mock of Test1Component interface.
type MockTest1Component struct {
	ctrl     *gomock.Controller
	recorder *MockTest1ComponentMockRecorder
}

// MockTest1ComponentMockRecorder is the mock recorder for MockTest1Component.
type MockTest1ComponentMockRecorder struct {
	mock *MockTest1Component
}

// NewMockTest1Component creates a new mock instance.
func NewMockTest1Component(ctrl *gomock.Controller) *MockTest1Component {
	mock := &MockTest1Component{ctrl: ctrl}
	mock.recorder = &MockTest1ComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTest1Component) EXPECT() *MockTest1ComponentMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockTest1Component) Foo(ctx context.Context, req *FooReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MockTest1ComponentMockRecorder) Foo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockTest1Component)(nil).Foo), ctx, req)
}

// MockTest2Component is a mock of Test2Component interface.
type MockTest2Component struct {
	ctrl     *gomock.Controller
	recorder *MockTest2ComponentMockRecorder
}

// MockTest2ComponentMockRecorder is the mock recorder for MockTest2Component.
type MockTest2ComponentMockRecorder struct {
	mock *MockTest2Component
}

// NewMockTest2Component creates a new mock instance.
func NewMockTest2Component(ctrl *gomock.Controller) *MockTest2Component {
	mock := &MockTest2Component{ctrl: ctrl}
	mock.recorder = &MockTest2ComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTest2Component) EXPECT() *MockTest2ComponentMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockTest2Component) Foo(ctx context.Context, req *FooReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MockTest2ComponentMockRecorder) Foo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockTest2Component)(nil).Foo), ctx, req)
}

// MockTest3Component is a mock of Test3Component interface.
type MockTest3Component struct {
	ctrl     *gomock.Controller
	recorder *MockTest3ComponentMockRecorder
}

// MockTest3ComponentMockRecorder is the mock recorder for MockTest3Component.
type MockTest3ComponentMockRecorder struct {
	mock *MockTest3Component
}

// NewMockTest3Component creates a new mock instance.
func NewMockTest3Component(ctrl *gomock.Controller) *MockTest3Component {
	mock := &MockTest3Component{ctrl: ctrl}
	mock.recorder = &MockTest3ComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTest3Component) EXPECT() *MockTest3ComponentMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockTest3Component) Foo(ctx context.Context, req *FooReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MockTest3ComponentMockRecorder) Foo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockTest3Component)(nil).Foo), ctx, req)
}
