version: 2

updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /tests
      - /examples
      - /ext
      - /interceptor
    labels:
      - dependencies
    schedule:
      interval: daily

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "daily"