version: 2

updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /tests
      - /examples
      - /ext
    labels:
      - dependencies
    schedule:
      interval: daily
    groups:
      gomod-normal-deps:
        update-types:
          - patch
          - minor
      gomod-breaking-deps:
        update-types:
          - major

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"
