codecov:
  notify:
    require_ci_to_pass: yes

component_management:
  default_rules:
    statuses:
      - type: patch
        target: auto
  individual_components:
    - component_id: kod
      name: kod
      paths:
        - "**"
        # - "!ext/**"
    # - component_id: kod-ext
    #   name: kod-ext
    #   paths:
    #     - "ext/**"
