version: '3'

tasks:
  default:
    cmds:
      - task: build:gowork
      - task: generate
      - task: mod
      - task: lint:golangci-lint

  github-action:
    cmds:
      - task: build:gowork
      - task: generate
      - task: lint:golangci-lint
      - task: lint:files-changed
      - task: test

  build:gowork:
    run: once
    sources:
      - /ext
      - /tests
      - /examples
      - /interceptor
    generates:
      - go.work
      - go.work.sum
    cmds:
      - go work init
      - go work use -r .

  build:kod:
    cmds:
      - go build -o kod ./cmd/kod
    sources:
      - "**/**.go"
    generates:
      - kod

  generate:struct2interface:
    cmds:
      - go run ./cmd/kod struct2interface .
    deps:
      - install:mockgen

  generate:
    cmds:
      - go run ./cmd/kod generate ./... ./tests/... ./examples/... ./ext/... ./interceptor/...
    deps:
      - generate:struct2interface

  lint:golangci-lint:
    cmd: |
        golangci-lint run ./...
    deps:
      - install:golangci-lint

  lint:files-changed:
    cmd: |
      git diff --exit-code

  test:
    cmd: |
        go test -race -cover -coverprofile=coverage.out -covermode=atomic ./... ./tests/... ./examples/... -coverpkg .,./cmd/...,./interceptor/...,./internal/...
    sources:
      - "**/**.go"
    generates:
      - coverage.out

  test:coverage:
    cmd: |
        go tool cover -func=coverage.out
    deps:
      - test

  install:mockgen:
    vars:
      VERSION: cat go.mod|grep go.uber.org/mock |awk -F ' ' '{print $2}'
    status:
      - go version -m $GOPATH/bin/mockgen | grep go.uber.org/mock | grep {{.VERSION}}
    cmd: |
        go install go.uber.org/mock/mockgen@{{.VERSION}}

  install:golangci-lint:
    vars:
      VERSION: v1.56.2
    status:
      - go version -m $GOPATH/bin/golangci-lint | grep github.com/golangci/golangci-lint | grep {{.VERSION}}
    cmd: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.VERSION}}

  mod:
    cmds:
      - go mod tidy
      - cd tests && go mod tidy
      - cd examples && go mod tidy
      - cd ext && go mod tidy
      - cd interceptor && go mod tidy