// Code generated by "kod generate". DO NOT EDIT.
//go:build !ignoreKodGen

package redis

import (
	"context"
	"github.com/go-kod/kod"
	"github.com/go-kod/kod/interceptor"
	"github.com/redis/go-redis/v9"
	"reflect"
)

func init() {
	kod.Register(&kod.Registration{
		Name:      "github.com/go-kod/kod/examples/redis/Component",
		Interface: reflect.TypeOf((*Component)(nil)).Elem(),
		Impl:      reflect.TypeOf(impl{}),
		Refs:      ``,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			var interceptors []kod.Interceptor
			if h, ok := info.Impl.(interface{ Interceptors() []kod.Interceptor }); ok {
				interceptors = h.Interceptors()
			}

			return component_local_stub{
				impl:        info.Impl.(Component),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
}

// kod.InstanceOf checks.
var _ kod.InstanceOf[Component] = (*impl)(nil)

// Local stub implementations.

type component_local_stub struct {
	impl        Component
	name        string
	interceptor kod.Interceptor
}

// Check that component_local_stub implements the Component interface.
var _ Component = (*component_local_stub)(nil)

func (s component_local_stub) Client() (r0 *redis.Client) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.Client()
	return
}
