// Code generated by kod struct2interface; DO NOT EDIT.

package snowflake

import (
	"context"
)

// impl is a component that implements Component.
type Component interface {
	// NextID returns a unique ID
	NextID(ctx context.Context, req *NextIDRequest) (*NextIDResponse, error)
}
