// Code generated by kod struct2interface; DO NOT EDIT.

package ranklist

import (
	"context"
)

// impl is a component that implements Component.
type Component interface {
	Add(ctx context.Context, req *AddRequest) error
	RankList(ctx context.Context, req *RankListRequest) ([]string, error)
}
