// Code generated by MockGen. DO NOT EDIT.
// Source: examples/domain/ranklist/kod_gen_interface.go
//
// Generated by this command:
//
//	mockgen -source examples/domain/ranklist/kod_gen_interface.go -destination examples/domain/ranklist/kod_gen_mock.go -package ranklist
//

// Package ranklist is a generated GoMock package.
package ranklist

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockComponent is a mock of Component interface.
type MockComponent struct {
	ctrl     *gomock.Controller
	recorder *MockComponentMockRecorder
}

// MockComponentMockRecorder is the mock recorder for MockComponent.
type MockComponentMockRecorder struct {
	mock *MockComponent
}

// NewMockComponent creates a new mock instance.
func NewMockComponent(ctrl *gomock.Controller) *MockComponent {
	mock := &MockComponent{ctrl: ctrl}
	mock.recorder = &MockComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponent) EXPECT() *MockComponentMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockComponent) Add(ctx context.Context, req *AddRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockComponentMockRecorder) Add(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockComponent)(nil).Add), ctx, req)
}

// RankList mocks base method.
func (m *MockComponent) RankList(ctx context.Context, req *RankListRequest) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankList", ctx, req)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankList indicates an expected call of RankList.
func (mr *MockComponentMockRecorder) RankList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankList", reflect.TypeOf((*MockComponent)(nil).RankList), ctx, req)
}
