// Code generated by "kod generate". DO NOT EDIT.
//go:build !ignoreKodGen

package user

import (
	"context"
	"github.com/go-kod/kod"
	"github.com/go-kod/kod/interceptor"
	"reflect"
)

func init() {
	kod.Register(&kod.Registration{
		Name:      "github.com/go-kod/kod/examples/domain/user/Component",
		Interface: reflect.TypeOf((*Component)(nil)).Elem(),
		Impl:      reflect.TypeOf(impl{}),
		Refs: `⟦8792a680:KoDeDgE:github.com/go-kod/kod/examples/domain/user/Component→github.com/go-kod/kod/examples/domain/snowflake/Component⟧,
⟦8bb50e61:KoDeDgE:github.com/go-kod/kod/examples/domain/user/Component→github.com/go-kod/kod/examples/infra/redis/Component⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			var interceptors []kod.Interceptor
			if h, ok := info.Impl.(interface{ Interceptors() []kod.Interceptor }); ok {
				interceptors = h.Interceptors()
			}

			return component_local_stub{
				impl:        info.Impl.(Component),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
}

// kod.InstanceOf checks.
var _ kod.InstanceOf[Component] = (*impl)(nil)

// Local stub implementations.

type component_local_stub struct {
	impl        Component
	name        string
	interceptor kod.Interceptor
}

// Check that component_local_stub implements the Component interface.
var _ Component = (*component_local_stub)(nil)

func (s component_local_stub) Auth(ctx context.Context, a1 *AuthRequest) (r0 *AuthResponse, err error) {

	if s.interceptor == nil {
		r0, err = s.impl.Auth(ctx, a1)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		r0, err = s.impl.Auth(ctx, a1)
		res[0] = r0
		return
	}

	info := kod.CallInfo{
		Impl:       s.impl,
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/examples/domain/user/Component.Auth",
		Method:     "Auth",
	}

	err = s.interceptor(ctx, info, []any{a1}, []any{r0}, call)
	return
}

func (s component_local_stub) DeRegister(ctx context.Context, a1 *DeRegisterRequest) (r0 *DeRegisterResponse, err error) {

	if s.interceptor == nil {
		r0, err = s.impl.DeRegister(ctx, a1)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		r0, err = s.impl.DeRegister(ctx, a1)
		res[0] = r0
		return
	}

	info := kod.CallInfo{
		Impl:       s.impl,
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/examples/domain/user/Component.DeRegister",
		Method:     "DeRegister",
	}

	err = s.interceptor(ctx, info, []any{a1}, []any{r0}, call)
	return
}

func (s component_local_stub) Login(ctx context.Context, a1 *LoginRequest) (r0 *LoginResponse, err error) {

	if s.interceptor == nil {
		r0, err = s.impl.Login(ctx, a1)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		r0, err = s.impl.Login(ctx, a1)
		res[0] = r0
		return
	}

	info := kod.CallInfo{
		Impl:       s.impl,
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/examples/domain/user/Component.Login",
		Method:     "Login",
	}

	err = s.interceptor(ctx, info, []any{a1}, []any{r0}, call)
	return
}

func (s component_local_stub) Register(ctx context.Context, a1 *RegisterRequest) (r0 *RegisterResponse, err error) {

	if s.interceptor == nil {
		r0, err = s.impl.Register(ctx, a1)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		r0, err = s.impl.Register(ctx, a1)
		res[0] = r0
		return
	}

	info := kod.CallInfo{
		Impl:       s.impl,
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/examples/domain/user/Component.Register",
		Method:     "Register",
	}

	err = s.interceptor(ctx, info, []any{a1}, []any{r0}, call)
	return
}
