// Code generated by kod struct2interface; DO NOT EDIT.

package case3

import (
	"context"
)

// Test1Component is a component interface implemented by [test1Component].
type Test1Component interface {
	Foo(ctx context.Context, req *FooReq) error
}

// Test2Component is a component interface implemented by [test2Component].
type Test2Component interface {
	Foo(ctx context.Context, req *FooReq) error
}

// Test3Component is a component interface implemented by [test3Component].
type Test3Component interface {
	Foo(ctx context.Context, req *FooReq) error
}
