// Code generated by kod struct2interface; DO NOT EDIT.

package case3

import (
	"context"
)

// test1Component is a component that implements Test1Component.
type Test1Component interface {
	Foo(ctx context.Context, req *FooReq) error
}

// test2Component is a component that implements Test2Component.
type Test2Component interface {
	Foo(ctx context.Context, req *FooReq) error
}

// test3Component is a component that implements Test3Component.
type Test3Component interface {
	Foo(ctx context.Context, req *FooReq) error
}
