// Code generated by "kod generate"; DO NOT EDIT.

package helloworld

import (
	"context"
)

// HelloWorld is implemented by [helloWorld],
// which can be mocked with [NewMockHelloWorld].
//
//	HelloWorld ...
type HelloWorld interface {
	// SayHello is implemented by [helloWorld.SayHello]
	//
	//	SayHello ...
	//	line two
	SayHello(ctx context.Context)
}

// HelloWorldLazy is implemented by [lazyHelloWorld],
// which can be mocked with [NewMockHelloWorldLazy].
type HelloWorldLazy interface {
	// SayHello is implemented by [lazyHelloWorld.SayHello]
	//
	//	SayHello ...
	SayHello(_ context.Context)
}

// HelloWorldInterceptor is implemented by [helloWorldInterceptor],
// which can be mocked with [NewMockHelloWorldInterceptor].
//
//	helloWorldInterceptor ...
type HelloWorldInterceptor interface {
	// SayHello is implemented by [helloWorldInterceptor.SayHello]
	//
	//	SayHello ...
	SayHello(_ context.Context)
}
