// Code generated by kod struct2interface; DO NOT EDIT.

package helloworld

import (
	"context"
)

// helloWorld is a component that implements HelloWorld.
type HelloWorld interface {
	SayHello(ctx context.Context)
}

// lazyHelloBob is a component that implements HelloLazy.
type HelloLazy interface {
	SayHello(ctx context.Context)
}
