// Code generated by kod struct2interface; DO NOT EDIT.

package helloworld

import (
	"context"
)

// helloWorld is a component that implements HelloWorld.
type HelloWorld interface {
	SayHello(ctx context.Context)
}

// lazyHelloWorld is a component that implements HelloWorldLazy.
type HelloWorldLazy interface {
	SayHello(ctx context.Context)
}

// helloWorldInterceptor is a component that implements HelloWorldInterceptor.
type HelloWorldInterceptor interface {
	SayHello(ctx context.Context)
}
