// Code generated by MockGen. DO NOT EDIT.
// Source: tests/case1/kod_gen_interface.go
//
// Generated by this command:
//
//	mockgen -source tests/case1/kod_gen_interface.go -destination tests/case1/kod_gen_mock.go -package case1 -typed
//

// Package case1 is a generated GoMock package.
package case1

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// Mocktest1Controller is a mock of test1Controller interface.
type Mocktest1Controller struct {
	ctrl     *gomock.Controller
	recorder *Mocktest1ControllerMockRecorder
}

// Mocktest1ControllerMockRecorder is the mock recorder for Mocktest1Controller.
type Mocktest1ControllerMockRecorder struct {
	mock *Mocktest1Controller
}

// NewMocktest1Controller creates a new mock instance.
func NewMocktest1Controller(ctrl *gomock.Controller) *Mocktest1Controller {
	mock := &Mocktest1Controller{ctrl: ctrl}
	mock.recorder = &Mocktest1ControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktest1Controller) EXPECT() *Mocktest1ControllerMockRecorder {
	return m.recorder
}

// MocktestService is a mock of testService interface.
type MocktestService struct {
	ctrl     *gomock.Controller
	recorder *MocktestServiceMockRecorder
}

// MocktestServiceMockRecorder is the mock recorder for MocktestService.
type MocktestServiceMockRecorder struct {
	mock *MocktestService
}

// NewMocktestService creates a new mock instance.
func NewMocktestService(ctrl *gomock.Controller) *MocktestService {
	mock := &MocktestService{ctrl: ctrl}
	mock.recorder = &MocktestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktestService) EXPECT() *MocktestServiceMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MocktestService) Foo(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MocktestServiceMockRecorder) Foo(ctx any) *MocktestServiceFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MocktestService)(nil).Foo), ctx)
	return &MocktestServiceFooCall{Call: call}
}

// MocktestServiceFooCall wrap *gomock.Call
type MocktestServiceFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktestServiceFooCall) Return(arg0 error) *MocktestServiceFooCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktestServiceFooCall) Do(f func(context.Context) error) *MocktestServiceFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktestServiceFooCall) DoAndReturn(f func(context.Context) error) *MocktestServiceFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MocktestRepository is a mock of testRepository interface.
type MocktestRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktestRepositoryMockRecorder
}

// MocktestRepositoryMockRecorder is the mock recorder for MocktestRepository.
type MocktestRepositoryMockRecorder struct {
	mock *MocktestRepository
}

// NewMocktestRepository creates a new mock instance.
func NewMocktestRepository(ctrl *gomock.Controller) *MocktestRepository {
	mock := &MocktestRepository{ctrl: ctrl}
	mock.recorder = &MocktestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktestRepository) EXPECT() *MocktestRepositoryMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MocktestRepository) Foo(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MocktestRepositoryMockRecorder) Foo(ctx any) *MocktestRepositoryFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MocktestRepository)(nil).Foo), ctx)
	return &MocktestRepositoryFooCall{Call: call}
}

// MocktestRepositoryFooCall wrap *gomock.Call
type MocktestRepositoryFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktestRepositoryFooCall) Return(arg0 error) *MocktestRepositoryFooCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktestRepositoryFooCall) Do(f func(context.Context) error) *MocktestRepositoryFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktestRepositoryFooCall) DoAndReturn(f func(context.Context) error) *MocktestRepositoryFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTest1Component is a mock of Test1Component interface.
type MockTest1Component struct {
	ctrl     *gomock.Controller
	recorder *MockTest1ComponentMockRecorder
}

// MockTest1ComponentMockRecorder is the mock recorder for MockTest1Component.
type MockTest1ComponentMockRecorder struct {
	mock *MockTest1Component
}

// NewMockTest1Component creates a new mock instance.
func NewMockTest1Component(ctrl *gomock.Controller) *MockTest1Component {
	mock := &MockTest1Component{ctrl: ctrl}
	mock.recorder = &MockTest1ComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTest1Component) EXPECT() *MockTest1ComponentMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockTest1Component) Foo(ctx context.Context, req *FooReq) (*FooRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx, req)
	ret0, _ := ret[0].(*FooRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Foo indicates an expected call of Foo.
func (mr *MockTest1ComponentMockRecorder) Foo(ctx, req any) *MockTest1ComponentFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockTest1Component)(nil).Foo), ctx, req)
	return &MockTest1ComponentFooCall{Call: call}
}

// MockTest1ComponentFooCall wrap *gomock.Call
type MockTest1ComponentFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTest1ComponentFooCall) Return(arg0 *FooRes, arg1 error) *MockTest1ComponentFooCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTest1ComponentFooCall) Do(f func(context.Context, *FooReq) (*FooRes, error)) *MockTest1ComponentFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTest1ComponentFooCall) DoAndReturn(f func(context.Context, *FooReq) (*FooRes, error)) *MockTest1ComponentFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTest2Component is a mock of Test2Component interface.
type MockTest2Component struct {
	ctrl     *gomock.Controller
	recorder *MockTest2ComponentMockRecorder
}

// MockTest2ComponentMockRecorder is the mock recorder for MockTest2Component.
type MockTest2ComponentMockRecorder struct {
	mock *MockTest2Component
}

// NewMockTest2Component creates a new mock instance.
func NewMockTest2Component(ctrl *gomock.Controller) *MockTest2Component {
	mock := &MockTest2Component{ctrl: ctrl}
	mock.recorder = &MockTest2ComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTest2Component) EXPECT() *MockTest2ComponentMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockTest2Component) GetClient() *http.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(*http.Client)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockTest2ComponentMockRecorder) GetClient() *MockTest2ComponentGetClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockTest2Component)(nil).GetClient))
	return &MockTest2ComponentGetClientCall{Call: call}
}

// MockTest2ComponentGetClientCall wrap *gomock.Call
type MockTest2ComponentGetClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTest2ComponentGetClientCall) Return(arg0 *http.Client) *MockTest2ComponentGetClientCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTest2ComponentGetClientCall) Do(f func() *http.Client) *MockTest2ComponentGetClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTest2ComponentGetClientCall) DoAndReturn(f func() *http.Client) *MockTest2ComponentGetClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockctxInterface is a mock of ctxInterface interface.
type MockctxInterface struct {
	ctrl     *gomock.Controller
	recorder *MockctxInterfaceMockRecorder
}

// MockctxInterfaceMockRecorder is the mock recorder for MockctxInterface.
type MockctxInterfaceMockRecorder struct {
	mock *MockctxInterface
}

// NewMockctxInterface creates a new mock instance.
func NewMockctxInterface(ctrl *gomock.Controller) *MockctxInterface {
	mock := &MockctxInterface{ctrl: ctrl}
	mock.recorder = &MockctxInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockctxInterface) EXPECT() *MockctxInterfaceMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockctxInterface) Foo(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Foo", ctx)
}

// Foo indicates an expected call of Foo.
func (mr *MockctxInterfaceMockRecorder) Foo(ctx any) *MockctxInterfaceFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockctxInterface)(nil).Foo), ctx)
	return &MockctxInterfaceFooCall{Call: call}
}

// MockctxInterfaceFooCall wrap *gomock.Call
type MockctxInterfaceFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockctxInterfaceFooCall) Return() *MockctxInterfaceFooCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockctxInterfaceFooCall) Do(f func(context.Context)) *MockctxInterfaceFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockctxInterfaceFooCall) DoAndReturn(f func(context.Context)) *MockctxInterfaceFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MocktestEchoController is a mock of testEchoController interface.
type MocktestEchoController struct {
	ctrl     *gomock.Controller
	recorder *MocktestEchoControllerMockRecorder
}

// MocktestEchoControllerMockRecorder is the mock recorder for MocktestEchoController.
type MocktestEchoControllerMockRecorder struct {
	mock *MocktestEchoController
}

// NewMocktestEchoController creates a new mock instance.
func NewMocktestEchoController(ctrl *gomock.Controller) *MocktestEchoController {
	mock := &MocktestEchoController{ctrl: ctrl}
	mock.recorder = &MocktestEchoControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktestEchoController) EXPECT() *MocktestEchoControllerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MocktestEchoController) Error(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MocktestEchoControllerMockRecorder) Error(c any) *MocktestEchoControllerErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MocktestEchoController)(nil).Error), c)
	return &MocktestEchoControllerErrorCall{Call: call}
}

// MocktestEchoControllerErrorCall wrap *gomock.Call
type MocktestEchoControllerErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MocktestEchoControllerErrorCall) Return(arg0 error) *MocktestEchoControllerErrorCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MocktestEchoControllerErrorCall) Do(f func(echo.Context) error) *MocktestEchoControllerErrorCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MocktestEchoControllerErrorCall) DoAndReturn(f func(echo.Context) error) *MocktestEchoControllerErrorCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// Hello mocks base method.
func (m *MocktestEchoController) Hello(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Hello indicates an expected call of Hello.
func (mr *MocktestEchoControllerMockRecorder) Hello(c any) *MocktestEchoControllerHelloCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MocktestEchoController)(nil).Hello), c)
	return &MocktestEchoControllerHelloCall{Call: call}
}

// MocktestEchoControllerHelloCall wrap *gomock.Call
type MocktestEchoControllerHelloCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MocktestEchoControllerHelloCall) Return(arg0 error) *MocktestEchoControllerHelloCall {
	c_2.Call = c_2.Call.Return(arg0)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MocktestEchoControllerHelloCall) Do(f func(echo.Context) error) *MocktestEchoControllerHelloCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MocktestEchoControllerHelloCall) DoAndReturn(f func(echo.Context) error) *MocktestEchoControllerHelloCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// MocktestGinController is a mock of testGinController interface.
type MocktestGinController struct {
	ctrl     *gomock.Controller
	recorder *MocktestGinControllerMockRecorder
}

// MocktestGinControllerMockRecorder is the mock recorder for MocktestGinController.
type MocktestGinControllerMockRecorder struct {
	mock *MocktestGinController
}

// NewMocktestGinController creates a new mock instance.
func NewMocktestGinController(ctrl *gomock.Controller) *MocktestGinController {
	mock := &MocktestGinController{ctrl: ctrl}
	mock.recorder = &MocktestGinControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktestGinController) EXPECT() *MocktestGinControllerMockRecorder {
	return m.recorder
}

// Hello mocks base method.
func (m *MocktestGinController) Hello(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Hello", c)
}

// Hello indicates an expected call of Hello.
func (mr *MocktestGinControllerMockRecorder) Hello(c any) *MocktestGinControllerHelloCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MocktestGinController)(nil).Hello), c)
	return &MocktestGinControllerHelloCall{Call: call}
}

// MocktestGinControllerHelloCall wrap *gomock.Call
type MocktestGinControllerHelloCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MocktestGinControllerHelloCall) Return() *MocktestGinControllerHelloCall {
	c_2.Call = c_2.Call.Return()
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MocktestGinControllerHelloCall) Do(f func(*gin.Context)) *MocktestGinControllerHelloCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MocktestGinControllerHelloCall) DoAndReturn(f func(*gin.Context)) *MocktestGinControllerHelloCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// MockHTTPController is a mock of HTTPController interface.
type MockHTTPController struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPControllerMockRecorder
}

// MockHTTPControllerMockRecorder is the mock recorder for MockHTTPController.
type MockHTTPControllerMockRecorder struct {
	mock *MockHTTPController
}

// NewMockHTTPController creates a new mock instance.
func NewMockHTTPController(ctrl *gomock.Controller) *MockHTTPController {
	mock := &MockHTTPController{ctrl: ctrl}
	mock.recorder = &MockHTTPControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPController) EXPECT() *MockHTTPControllerMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockHTTPController) Foo(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Foo", w, r)
}

// Foo indicates an expected call of Foo.
func (mr *MockHTTPControllerMockRecorder) Foo(w, r any) *MockHTTPControllerFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockHTTPController)(nil).Foo), w, r)
	return &MockHTTPControllerFooCall{Call: call}
}

// MockHTTPControllerFooCall wrap *gomock.Call
type MockHTTPControllerFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPControllerFooCall) Return() *MockHTTPControllerFooCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPControllerFooCall) Do(f func(http.ResponseWriter, *http.Request)) *MockHTTPControllerFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPControllerFooCall) DoAndReturn(f func(http.ResponseWriter, *http.Request)) *MockHTTPControllerFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockInterceptorRetry is a mock of InterceptorRetry interface.
type MockInterceptorRetry struct {
	ctrl     *gomock.Controller
	recorder *MockInterceptorRetryMockRecorder
}

// MockInterceptorRetryMockRecorder is the mock recorder for MockInterceptorRetry.
type MockInterceptorRetryMockRecorder struct {
	mock *MockInterceptorRetry
}

// NewMockInterceptorRetry creates a new mock instance.
func NewMockInterceptorRetry(ctrl *gomock.Controller) *MockInterceptorRetry {
	mock := &MockInterceptorRetry{ctrl: ctrl}
	mock.recorder = &MockInterceptorRetryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterceptorRetry) EXPECT() *MockInterceptorRetryMockRecorder {
	return m.recorder
}

// TestError mocks base method.
func (m *MockInterceptorRetry) TestError(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestError", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestError indicates an expected call of TestError.
func (mr *MockInterceptorRetryMockRecorder) TestError(ctx any) *MockInterceptorRetryTestErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestError", reflect.TypeOf((*MockInterceptorRetry)(nil).TestError), ctx)
	return &MockInterceptorRetryTestErrorCall{Call: call}
}

// MockInterceptorRetryTestErrorCall wrap *gomock.Call
type MockInterceptorRetryTestErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInterceptorRetryTestErrorCall) Return(arg0 error) *MockInterceptorRetryTestErrorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInterceptorRetryTestErrorCall) Do(f func(context.Context) error) *MockInterceptorRetryTestErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInterceptorRetryTestErrorCall) DoAndReturn(f func(context.Context) error) *MockInterceptorRetryTestErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TestNormal mocks base method.
func (m *MockInterceptorRetry) TestNormal(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestNormal", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestNormal indicates an expected call of TestNormal.
func (mr *MockInterceptorRetryMockRecorder) TestNormal(ctx any) *MockInterceptorRetryTestNormalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestNormal", reflect.TypeOf((*MockInterceptorRetry)(nil).TestNormal), ctx)
	return &MockInterceptorRetryTestNormalCall{Call: call}
}

// MockInterceptorRetryTestNormalCall wrap *gomock.Call
type MockInterceptorRetryTestNormalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInterceptorRetryTestNormalCall) Return(arg0 error) *MockInterceptorRetryTestNormalCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInterceptorRetryTestNormalCall) Do(f func(context.Context) error) *MockInterceptorRetryTestNormalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInterceptorRetryTestNormalCall) DoAndReturn(f func(context.Context) error) *MockInterceptorRetryTestNormalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockLazyInitImpl is a mock of LazyInitImpl interface.
type MockLazyInitImpl struct {
	ctrl     *gomock.Controller
	recorder *MockLazyInitImplMockRecorder
}

// MockLazyInitImplMockRecorder is the mock recorder for MockLazyInitImpl.
type MockLazyInitImplMockRecorder struct {
	mock *MockLazyInitImpl
}

// NewMockLazyInitImpl creates a new mock instance.
func NewMockLazyInitImpl(ctrl *gomock.Controller) *MockLazyInitImpl {
	mock := &MockLazyInitImpl{ctrl: ctrl}
	mock.recorder = &MockLazyInitImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLazyInitImpl) EXPECT() *MockLazyInitImplMockRecorder {
	return m.recorder
}

// Try mocks base method.
func (m *MockLazyInitImpl) Try(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Try", ctx)
}

// Try indicates an expected call of Try.
func (mr *MockLazyInitImplMockRecorder) Try(ctx any) *MockLazyInitImplTryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Try", reflect.TypeOf((*MockLazyInitImpl)(nil).Try), ctx)
	return &MockLazyInitImplTryCall{Call: call}
}

// MockLazyInitImplTryCall wrap *gomock.Call
type MockLazyInitImplTryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLazyInitImplTryCall) Return() *MockLazyInitImplTryCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLazyInitImplTryCall) Do(f func(context.Context)) *MockLazyInitImplTryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLazyInitImplTryCall) DoAndReturn(f func(context.Context)) *MockLazyInitImplTryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockLazyInitComponent is a mock of LazyInitComponent interface.
type MockLazyInitComponent struct {
	ctrl     *gomock.Controller
	recorder *MockLazyInitComponentMockRecorder
}

// MockLazyInitComponentMockRecorder is the mock recorder for MockLazyInitComponent.
type MockLazyInitComponentMockRecorder struct {
	mock *MockLazyInitComponent
}

// NewMockLazyInitComponent creates a new mock instance.
func NewMockLazyInitComponent(ctrl *gomock.Controller) *MockLazyInitComponent {
	mock := &MockLazyInitComponent{ctrl: ctrl}
	mock.recorder = &MockLazyInitComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLazyInitComponent) EXPECT() *MockLazyInitComponentMockRecorder {
	return m.recorder
}

// Try mocks base method.
func (m *MockLazyInitComponent) Try(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Try", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Try indicates an expected call of Try.
func (mr *MockLazyInitComponentMockRecorder) Try(ctx any) *MockLazyInitComponentTryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Try", reflect.TypeOf((*MockLazyInitComponent)(nil).Try), ctx)
	return &MockLazyInitComponentTryCall{Call: call}
}

// MockLazyInitComponentTryCall wrap *gomock.Call
type MockLazyInitComponentTryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLazyInitComponentTryCall) Return(arg0 error) *MockLazyInitComponentTryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLazyInitComponentTryCall) Do(f func(context.Context) error) *MockLazyInitComponentTryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLazyInitComponentTryCall) DoAndReturn(f func(context.Context) error) *MockLazyInitComponentTryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockpanicCaseInterface is a mock of panicCaseInterface interface.
type MockpanicCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockpanicCaseInterfaceMockRecorder
}

// MockpanicCaseInterfaceMockRecorder is the mock recorder for MockpanicCaseInterface.
type MockpanicCaseInterfaceMockRecorder struct {
	mock *MockpanicCaseInterface
}

// NewMockpanicCaseInterface creates a new mock instance.
func NewMockpanicCaseInterface(ctrl *gomock.Controller) *MockpanicCaseInterface {
	mock := &MockpanicCaseInterface{ctrl: ctrl}
	mock.recorder = &MockpanicCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpanicCaseInterface) EXPECT() *MockpanicCaseInterfaceMockRecorder {
	return m.recorder
}

// TestPanic mocks base method.
func (m *MockpanicCaseInterface) TestPanic(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TestPanic", ctx)
}

// TestPanic indicates an expected call of TestPanic.
func (mr *MockpanicCaseInterfaceMockRecorder) TestPanic(ctx any) *MockpanicCaseInterfaceTestPanicCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestPanic", reflect.TypeOf((*MockpanicCaseInterface)(nil).TestPanic), ctx)
	return &MockpanicCaseInterfaceTestPanicCall{Call: call}
}

// MockpanicCaseInterfaceTestPanicCall wrap *gomock.Call
type MockpanicCaseInterfaceTestPanicCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpanicCaseInterfaceTestPanicCall) Return() *MockpanicCaseInterfaceTestPanicCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpanicCaseInterfaceTestPanicCall) Do(f func(context.Context)) *MockpanicCaseInterfaceTestPanicCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpanicCaseInterfaceTestPanicCall) DoAndReturn(f func(context.Context)) *MockpanicCaseInterfaceTestPanicCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockpanicNoRecvoeryCaseInterface is a mock of panicNoRecvoeryCaseInterface interface.
type MockpanicNoRecvoeryCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockpanicNoRecvoeryCaseInterfaceMockRecorder
}

// MockpanicNoRecvoeryCaseInterfaceMockRecorder is the mock recorder for MockpanicNoRecvoeryCaseInterface.
type MockpanicNoRecvoeryCaseInterfaceMockRecorder struct {
	mock *MockpanicNoRecvoeryCaseInterface
}

// NewMockpanicNoRecvoeryCaseInterface creates a new mock instance.
func NewMockpanicNoRecvoeryCaseInterface(ctrl *gomock.Controller) *MockpanicNoRecvoeryCaseInterface {
	mock := &MockpanicNoRecvoeryCaseInterface{ctrl: ctrl}
	mock.recorder = &MockpanicNoRecvoeryCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpanicNoRecvoeryCaseInterface) EXPECT() *MockpanicNoRecvoeryCaseInterfaceMockRecorder {
	return m.recorder
}

// TestPanic mocks base method.
func (m *MockpanicNoRecvoeryCaseInterface) TestPanic(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TestPanic", ctx)
}

// TestPanic indicates an expected call of TestPanic.
func (mr *MockpanicNoRecvoeryCaseInterfaceMockRecorder) TestPanic(ctx any) *MockpanicNoRecvoeryCaseInterfaceTestPanicCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestPanic", reflect.TypeOf((*MockpanicNoRecvoeryCaseInterface)(nil).TestPanic), ctx)
	return &MockpanicNoRecvoeryCaseInterfaceTestPanicCall{Call: call}
}

// MockpanicNoRecvoeryCaseInterfaceTestPanicCall wrap *gomock.Call
type MockpanicNoRecvoeryCaseInterfaceTestPanicCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpanicNoRecvoeryCaseInterfaceTestPanicCall) Return() *MockpanicNoRecvoeryCaseInterfaceTestPanicCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpanicNoRecvoeryCaseInterfaceTestPanicCall) Do(f func(context.Context)) *MockpanicNoRecvoeryCaseInterfaceTestPanicCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpanicNoRecvoeryCaseInterfaceTestPanicCall) DoAndReturn(f func(context.Context)) *MockpanicNoRecvoeryCaseInterfaceTestPanicCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
