// Code generated by kod struct2interface; DO NOT EDIT.

package case1

import (
	"context"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/labstack/echo/v4"
)

// test1Controller is a component interface implemented by [test1ControllerImpl].
type test1Controller interface {
}

// testService is a component interface implemented by [serviceImpl].
type testService interface {
	Foo(ctx context.Context) error
}

// testRepository is a component interface implemented by [modelImpl].
type testRepository interface {
	Foo(ctx context.Context) error
}

// Test1Component is a component interface implemented by [test1Component].
type Test1Component interface {
	Foo(ctx context.Context, req *FooReq) (*FooRes, error)
}

// Test2Component is a component interface implemented by [test2Component].
type Test2Component interface {
	GetClient() *http.Client
}

// ctxInterface is a component interface implemented by [ctxImpl].
type ctxInterface interface {
	// Foo is a http handler
	Foo(ctx context.Context)
}

// testEchoController is a component interface implemented by [testEchoControllerImpl].
type testEchoController interface {
	// Hello is a method of testEchoControllerImpl
	Hello(c echo.Context) error
	// Error is a method of testEchoControllerImpl
	Error(c echo.Context) error
}

// testGinController is a component interface implemented by [testGinControllerImpl].
type testGinController interface {
	// Hello is a method of testGinControllerImpl
	Hello(c *gin.Context)
}

// HTTPController is a component interface implemented by [httpControllerImpl].
type HTTPController interface {
	// Foo is a http handler
	Foo(w http.ResponseWriter, r *http.Request)
}

// InterceptorRetry is a component interface implemented by [interceptorRetry].
type InterceptorRetry interface {
	TestError(ctx context.Context) error
	TestNormal(ctx context.Context) error
}

// LazyInitImpl is a component interface implemented by [lazyInitImpl].
type LazyInitImpl interface {
	Try(ctx context.Context)
}

// LazyInitComponent is a component interface implemented by [lazyInitComponent].
type LazyInitComponent interface {
	Try(ctx context.Context) error
}

// panicCaseInterface is a component interface implemented by [panicCase].
type panicCaseInterface interface {
	TestPanic(ctx context.Context)
}

// panicNoRecvoeryCaseInterface is a component interface implemented by [panicNoRecvoeryCase].
type panicNoRecvoeryCaseInterface interface {
	TestPanic(ctx context.Context)
}
