// Code generated by MockGen. DO NOT EDIT.
// Source: examples/infra/redis/kod_gen_interface.go
//
// Generated by this command:
//
//	mockgen -source examples/infra/redis/kod_gen_interface.go -destination examples/infra/redis/kod_gen_mock.go -package redis
//
// Package redis is a generated GoMock package.
package redis

import (
	reflect "reflect"

	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockComponent is a mock of Component interface.
type MockComponent struct {
	ctrl     *gomock.Controller
	recorder *MockComponentMockRecorder
}

// MockComponentMockRecorder is the mock recorder for MockComponent.
type MockComponentMockRecorder struct {
	mock *MockComponent
}

// NewMockComponent creates a new mock instance.
func NewMockComponent(ctrl *gomock.Controller) *MockComponent {
	mock := &MockComponent{ctrl: ctrl}
	mock.recorder = &MockComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponent) EXPECT() *MockComponentMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockComponent) Client() *redis.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(*redis.Client)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockComponentMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockComponent)(nil).Client))
}
