// Code generated by kod struct2interface; DO NOT EDIT.

package redis

import (
	goredis "github.com/redis/go-redis/v9"
)

// impl is a component that implements Component.
type Component interface {
	Client() *goredis.Client
}
