// Code generated by kod struct2interface; DO NOT EDIT.

package case5

// TestRefStruct1 is implemented by [testRefStruct1],
// which can be mocked with [NewMockTestRefStruct1].
type TestRefStruct1 interface {
}
