//go:build !ignoreKodGen

// Code generated by MockGen. DO NOT EDIT.
// Source: tests/case5/kod_gen_interface.go
//
// Generated by this command:
//
//	mockgen -source tests/case5/kod_gen_interface.go -destination tests/case5/kod_gen_mock.go -package case5 -typed -build_constraint !ignoreKodGen
//

// Package case5 is a generated GoMock package.
package case5

import (
	gomock "go.uber.org/mock/gomock"
)

// MockTestRefStruct1 is a mock of TestRefStruct1 interface.
type MockTestRefStruct1 struct {
	ctrl     *gomock.Controller
	recorder *MockTestRefStruct1MockRecorder
	isgomock struct{}
}

// MockTestRefStruct1MockRecorder is the mock recorder for MockTestRefStruct1.
type MockTestRefStruct1MockRecorder struct {
	mock *MockTestRefStruct1
}

// NewMockTestRefStruct1 creates a new mock instance.
func NewMockTestRefStruct1(ctrl *gomock.Controller) *MockTestRefStruct1 {
	mock := &MockTestRefStruct1{ctrl: ctrl}
	mock.recorder = &MockTestRefStruct1MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestRefStruct1) EXPECT() *MockTestRefStruct1MockRecorder {
	return m.recorder
}
