// Code generated by "kod generate". DO NOT EDIT.
//go:build !ignoreKodGen

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/go-kod/kod"
	"github.com/go-kod/kod/interceptor"
	"net/http"
	"reflect"
)

func init() {
	kod.Register(kod.Registration{
		Name:  "github.com/go-kod/kod/tests/graphcase/HTTPController",
		Iface: reflect.TypeOf((*HTTPController)(nil)).Elem(),
		Impl:  reflect.TypeOf(httpControllerImpl{}),
		Refs:  `⟦38b48264:KoDeDgE:github.com/go-kod/kod/tests/graphcase/HTTPController→github.com/go-kod/kod/tests/graphcase/testService⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			var interceptors []kod.Interceptor
			if h, ok := info.Impl.(interface{ Interceptors() []kod.Interceptor }); ok {
				interceptors = h.Interceptors()
			}

			return hTTPController_local_stub{
				impl:        info.Impl.(HTTPController),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(kod.Registration{
		Name:  "github.com/go-kod/kod/Main",
		Iface: reflect.TypeOf((*kod.Main)(nil)).Elem(),
		Impl:  reflect.TypeOf(App{}),
		Refs: `⟦b628eb85:KoDeDgE:github.com/go-kod/kod/Main→github.com/go-kod/kod/tests/graphcase/test1Controller⟧,
⟦75680c21:KoDeDgE:github.com/go-kod/kod/Main→github.com/go-kod/kod/tests/graphcase/Test1Component⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			var interceptors []kod.Interceptor
			if h, ok := info.Impl.(interface{ Interceptors() []kod.Interceptor }); ok {
				interceptors = h.Interceptors()
			}

			return main_local_stub{
				impl:        info.Impl.(kod.Main),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(kod.Registration{
		Name:  "github.com/go-kod/kod/tests/graphcase/Test1Component",
		Iface: reflect.TypeOf((*Test1Component)(nil)).Elem(),
		Impl:  reflect.TypeOf(test1Component{}),
		Refs:  ``,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			var interceptors []kod.Interceptor
			if h, ok := info.Impl.(interface{ Interceptors() []kod.Interceptor }); ok {
				interceptors = h.Interceptors()
			}

			return test1Component_local_stub{
				impl:        info.Impl.(Test1Component),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(kod.Registration{
		Name:  "github.com/go-kod/kod/tests/graphcase/test1Controller",
		Iface: reflect.TypeOf((*test1Controller)(nil)).Elem(),
		Impl:  reflect.TypeOf(test1ControllerImpl{}),
		Refs: `⟦54c533d5:KoDeDgE:github.com/go-kod/kod/tests/graphcase/test1Controller→github.com/go-kod/kod/tests/graphcase/HTTPController⟧,
⟦f932c69a:KoDeDgE:github.com/go-kod/kod/tests/graphcase/test1Controller→github.com/go-kod/kod/tests/graphcase/Test1Component⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			var interceptors []kod.Interceptor
			if h, ok := info.Impl.(interface{ Interceptors() []kod.Interceptor }); ok {
				interceptors = h.Interceptors()
			}

			return test1Controller_local_stub{
				impl:        info.Impl.(test1Controller),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(kod.Registration{
		Name:  "github.com/go-kod/kod/tests/graphcase/testModel",
		Iface: reflect.TypeOf((*testModel)(nil)).Elem(),
		Impl:  reflect.TypeOf(modelImpl{}),
		Refs:  ``,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			var interceptors []kod.Interceptor
			if h, ok := info.Impl.(interface{ Interceptors() []kod.Interceptor }); ok {
				interceptors = h.Interceptors()
			}

			return testModel_local_stub{
				impl:        info.Impl.(testModel),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(kod.Registration{
		Name:  "github.com/go-kod/kod/tests/graphcase/testService",
		Iface: reflect.TypeOf((*testService)(nil)).Elem(),
		Impl:  reflect.TypeOf(serviceImpl{}),
		Refs:  `⟦e691e13e:KoDeDgE:github.com/go-kod/kod/tests/graphcase/testService→github.com/go-kod/kod/tests/graphcase/testModel⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			var interceptors []kod.Interceptor
			if h, ok := info.Impl.(interface{ Interceptors() []kod.Interceptor }); ok {
				interceptors = h.Interceptors()
			}

			return testService_local_stub{
				impl:        info.Impl.(testService),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
}

// kod.InstanceOf checks.
var _ kod.InstanceOf[HTTPController] = (*httpControllerImpl)(nil)
var _ kod.InstanceOf[kod.Main] = (*App)(nil)
var _ kod.InstanceOf[Test1Component] = (*test1Component)(nil)
var _ kod.InstanceOf[test1Controller] = (*test1ControllerImpl)(nil)
var _ kod.InstanceOf[testModel] = (*modelImpl)(nil)
var _ kod.InstanceOf[testService] = (*serviceImpl)(nil)

// Local stub implementations.

type hTTPController_local_stub struct {
	impl        HTTPController
	name        string
	interceptor kod.Interceptor
}

// Check that hTTPController_local_stub implements the HTTPController interface.
var _ HTTPController = (*hTTPController_local_stub)(nil)

func (s hTTPController_local_stub) Foo(a0 http.ResponseWriter, a1 http.Request) {

	if s.interceptor == nil {
		s.impl.Foo(a0, a1)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		s.impl.Foo(a0, a1)
		return
	}

	info := kod.CallInfo{
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/tests/graphcase/HTTPController.Foo",
		Method:     "Foo",
	}

	ctx := context.Background()
	_ = s.interceptor(ctx, info, []any{a0, a1}, []any{}, call)
}

type main_local_stub struct {
	impl        kod.Main
	name        string
	interceptor kod.Interceptor
}

// Check that main_local_stub implements the kod.Main interface.
var _ kod.Main = (*main_local_stub)(nil)

type test1Component_local_stub struct {
	impl        Test1Component
	name        string
	interceptor kod.Interceptor
}

// Check that test1Component_local_stub implements the Test1Component interface.
var _ Test1Component = (*test1Component_local_stub)(nil)

func (s test1Component_local_stub) Foo(ctx context.Context, a1 *FooReq) (err error) {

	if s.interceptor == nil {
		err = s.impl.Foo(ctx, a1)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		err = s.impl.Foo(ctx, a1)
		return
	}

	info := kod.CallInfo{
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/tests/graphcase/Test1Component.Foo",
		Method:     "Foo",
	}

	err = s.interceptor(ctx, info, []any{a1}, []any{}, call)
	return
}

type test1Controller_local_stub struct {
	impl        test1Controller
	name        string
	interceptor kod.Interceptor
}

// Check that test1Controller_local_stub implements the test1Controller interface.
var _ test1Controller = (*test1Controller_local_stub)(nil)

func (s test1Controller_local_stub) Foo(a0 *gin.Context) {

	if s.interceptor == nil {
		s.impl.Foo(a0)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		a0.Request = a0.Request.WithContext(ctx)
		s.impl.Foo(a0)
		return
	}

	info := kod.CallInfo{
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/tests/graphcase/test1Controller.Foo",
		Method:     "Foo",
	}

	var err error
	ctx := a0.Request.Context()
	err = s.interceptor(ctx, info, []any{a0}, []any{}, call)
	if err != nil {
		a0.Error(err)
	}
}

type testModel_local_stub struct {
	impl        testModel
	name        string
	interceptor kod.Interceptor
}

// Check that testModel_local_stub implements the testModel interface.
var _ testModel = (*testModel_local_stub)(nil)

func (s testModel_local_stub) Foo(ctx context.Context) (err error) {

	if s.interceptor == nil {
		err = s.impl.Foo(ctx)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		err = s.impl.Foo(ctx)
		return
	}

	info := kod.CallInfo{
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/tests/graphcase/testModel.Foo",
		Method:     "Foo",
	}

	err = s.interceptor(ctx, info, []any{}, []any{}, call)
	return
}

type testService_local_stub struct {
	impl        testService
	name        string
	interceptor kod.Interceptor
}

// Check that testService_local_stub implements the testService interface.
var _ testService = (*testService_local_stub)(nil)

func (s testService_local_stub) Foo(ctx context.Context) (err error) {

	if s.interceptor == nil {
		err = s.impl.Foo(ctx)
		return
	}

	call := func(ctx context.Context, info kod.CallInfo, req, res []any) (err error) {
		err = s.impl.Foo(ctx)
		return
	}

	info := kod.CallInfo{
		Component:  s.name,
		FullMethod: "github.com/go-kod/kod/tests/graphcase/testService.Foo",
		Method:     "Foo",
	}

	err = s.interceptor(ctx, info, []any{}, []any{}, call)
	return
}
