// Code generated by MockGen. DO NOT EDIT.
// Source: tests/graphcase/kod_gen_interface.go
//
// Generated by this command:
//
//	mockgen -source tests/graphcase/kod_gen_interface.go -destination tests/graphcase/kod_gen_mock.go -package main -typed
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// Mocktest1Controller is a mock of test1Controller interface.
type Mocktest1Controller struct {
	ctrl     *gomock.Controller
	recorder *Mocktest1ControllerMockRecorder
	isgomock struct{}
}

// Mocktest1ControllerMockRecorder is the mock recorder for Mocktest1Controller.
type Mocktest1ControllerMockRecorder struct {
	mock *Mocktest1Controller
}

// NewMocktest1Controller creates a new mock instance.
func NewMocktest1Controller(ctrl *gomock.Controller) *Mocktest1Controller {
	mock := &Mocktest1Controller{ctrl: ctrl}
	mock.recorder = &Mocktest1ControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktest1Controller) EXPECT() *Mocktest1ControllerMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *Mocktest1Controller) Foo(cccccc *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Foo", cccccc)
}

// Foo indicates an expected call of Foo.
func (mr *Mocktest1ControllerMockRecorder) Foo(cccccc any) *Mocktest1ControllerFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*Mocktest1Controller)(nil).Foo), cccccc)
	return &Mocktest1ControllerFooCall{Call: call}
}

// Mocktest1ControllerFooCall wrap *gomock.Call
type Mocktest1ControllerFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *Mocktest1ControllerFooCall) Return() *Mocktest1ControllerFooCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *Mocktest1ControllerFooCall) Do(f func(*gin.Context)) *Mocktest1ControllerFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *Mocktest1ControllerFooCall) DoAndReturn(f func(*gin.Context)) *Mocktest1ControllerFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHTTPController is a mock of HTTPController interface.
type MockHTTPController struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPControllerMockRecorder
	isgomock struct{}
}

// MockHTTPControllerMockRecorder is the mock recorder for MockHTTPController.
type MockHTTPControllerMockRecorder struct {
	mock *MockHTTPController
}

// NewMockHTTPController creates a new mock instance.
func NewMockHTTPController(ctrl *gomock.Controller) *MockHTTPController {
	mock := &MockHTTPController{ctrl: ctrl}
	mock.recorder = &MockHTTPControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPController) EXPECT() *MockHTTPControllerMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockHTTPController) Foo(w http.ResponseWriter, r http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Foo", w, r)
}

// Foo indicates an expected call of Foo.
func (mr *MockHTTPControllerMockRecorder) Foo(w, r any) *MockHTTPControllerFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockHTTPController)(nil).Foo), w, r)
	return &MockHTTPControllerFooCall{Call: call}
}

// MockHTTPControllerFooCall wrap *gomock.Call
type MockHTTPControllerFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPControllerFooCall) Return() *MockHTTPControllerFooCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPControllerFooCall) Do(f func(http.ResponseWriter, http.Request)) *MockHTTPControllerFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPControllerFooCall) DoAndReturn(f func(http.ResponseWriter, http.Request)) *MockHTTPControllerFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MocktestService is a mock of testService interface.
type MocktestService struct {
	ctrl     *gomock.Controller
	recorder *MocktestServiceMockRecorder
	isgomock struct{}
}

// MocktestServiceMockRecorder is the mock recorder for MocktestService.
type MocktestServiceMockRecorder struct {
	mock *MocktestService
}

// NewMocktestService creates a new mock instance.
func NewMocktestService(ctrl *gomock.Controller) *MocktestService {
	mock := &MocktestService{ctrl: ctrl}
	mock.recorder = &MocktestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktestService) EXPECT() *MocktestServiceMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MocktestService) Foo(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MocktestServiceMockRecorder) Foo(ctx any) *MocktestServiceFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MocktestService)(nil).Foo), ctx)
	return &MocktestServiceFooCall{Call: call}
}

// MocktestServiceFooCall wrap *gomock.Call
type MocktestServiceFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktestServiceFooCall) Return(arg0 error) *MocktestServiceFooCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktestServiceFooCall) Do(f func(context.Context) error) *MocktestServiceFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktestServiceFooCall) DoAndReturn(f func(context.Context) error) *MocktestServiceFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MocktestModel is a mock of testModel interface.
type MocktestModel struct {
	ctrl     *gomock.Controller
	recorder *MocktestModelMockRecorder
	isgomock struct{}
}

// MocktestModelMockRecorder is the mock recorder for MocktestModel.
type MocktestModelMockRecorder struct {
	mock *MocktestModel
}

// NewMocktestModel creates a new mock instance.
func NewMocktestModel(ctrl *gomock.Controller) *MocktestModel {
	mock := &MocktestModel{ctrl: ctrl}
	mock.recorder = &MocktestModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktestModel) EXPECT() *MocktestModelMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MocktestModel) Foo(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MocktestModelMockRecorder) Foo(ctx any) *MocktestModelFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MocktestModel)(nil).Foo), ctx)
	return &MocktestModelFooCall{Call: call}
}

// MocktestModelFooCall wrap *gomock.Call
type MocktestModelFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktestModelFooCall) Return(arg0 error) *MocktestModelFooCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktestModelFooCall) Do(f func(context.Context) error) *MocktestModelFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktestModelFooCall) DoAndReturn(f func(context.Context) error) *MocktestModelFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTest1Component is a mock of Test1Component interface.
type MockTest1Component struct {
	ctrl     *gomock.Controller
	recorder *MockTest1ComponentMockRecorder
	isgomock struct{}
}

// MockTest1ComponentMockRecorder is the mock recorder for MockTest1Component.
type MockTest1ComponentMockRecorder struct {
	mock *MockTest1Component
}

// NewMockTest1Component creates a new mock instance.
func NewMockTest1Component(ctrl *gomock.Controller) *MockTest1Component {
	mock := &MockTest1Component{ctrl: ctrl}
	mock.recorder = &MockTest1ComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTest1Component) EXPECT() *MockTest1ComponentMockRecorder {
	return m.recorder
}

// Foo mocks base method.
func (m *MockTest1Component) Foo(ctx context.Context, req *FooReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Foo", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Foo indicates an expected call of Foo.
func (mr *MockTest1ComponentMockRecorder) Foo(ctx, req any) *MockTest1ComponentFooCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Foo", reflect.TypeOf((*MockTest1Component)(nil).Foo), ctx, req)
	return &MockTest1ComponentFooCall{Call: call}
}

// MockTest1ComponentFooCall wrap *gomock.Call
type MockTest1ComponentFooCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTest1ComponentFooCall) Return(arg0 error) *MockTest1ComponentFooCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTest1ComponentFooCall) Do(f func(context.Context, *FooReq) error) *MockTest1ComponentFooCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTest1ComponentFooCall) DoAndReturn(f func(context.Context, *FooReq) error) *MockTest1ComponentFooCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
