// Code generated by kod struct2interface; DO NOT EDIT.

package main

import (
	"context"
	"net/http"

	"github.com/gin-gonic/gin"
)

// test1Controller is a component interface implemented by [test1ControllerImpl].
type test1Controller interface {
	Foo(cccccc *gin.Context)
}

// HTTPController is a component interface implemented by [httpControllerImpl].
type HTTPController interface {
	Foo(w http.ResponseWriter, r http.Request)
}

// testService is a component interface implemented by [serviceImpl].
type testService interface {
	Foo(ctx context.Context) error
}

// testModel is a component interface implemented by [modelImpl].
type testModel interface {
	Foo(ctx context.Context) error
}

// Test1Component is a component interface implemented by [test1Component].
type Test1Component interface {
	Foo(ctx context.Context, req *FooReq) error
}
