// Code generated by kod struct2interface; DO NOT EDIT.

package main

import (
	"context"
	"net/http"

	"github.com/gin-gonic/gin"
)

// test1Controller is implemented by [test1ControllerImpl],
// which can be mocked with [NewMocktest1Controller].
type test1Controller interface {
	// Foo is implemented by [test1ControllerImpl.Foo]
	Foo(cccccc *gin.Context)
}

// HTTPController is implemented by [httpControllerImpl],
// which can be mocked with [NewMockHTTPController].
type HTTPController interface {
	// Foo is implemented by [httpControllerImpl.Foo]
	Foo(w http.ResponseWriter, r http.Request)
}

// testService is implemented by [serviceImpl],
// which can be mocked with [NewMocktestService].
type testService interface {
	// Foo is implemented by [serviceImpl.Foo]
	Foo(ctx context.Context) error
}

// testModel is implemented by [modelImpl],
// which can be mocked with [NewMocktestModel].
type testModel interface {
	// Foo is implemented by [modelImpl.Foo]
	Foo(ctx context.Context) error
}

// Test1Component is implemented by [test1Component],
// which can be mocked with [NewMockTest1Component].
type Test1Component interface {
	// Foo is implemented by [test1Component.Foo]
	Foo(ctx context.Context, req *FooReq) error
}
