// Code generated by kod struct2interface; DO NOT EDIT.

package shorturl

import (
	"context"
)

// impl is a component that implements Component.
type Component interface {
	// Generate generates a short url.
	Generate(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error)
	// Get gets the original url from short url.
	Get(ctx context.Context, req *GetRequest) (*GetResponse, error)
}
