// Code generated by kod struct2interface; DO NOT EDIT.

package user

import (
	"context"
)

// impl is a component that implements Component.
type Component interface {
	// Register register a user
	Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error)
	// DeRegister deregister a user
	DeRegister(ctx context.Context, req *DeRegisterRequest) (*DeRegisterResponse, error)
	// Login login a user with jwt
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
	// Auth auth a user with jwt
	Auth(ctx context.Context, req *AuthRequest) (*AuthResponse, error)
}
