name: Release

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 0 * * *'  # 每天0点触发
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Tag release
            goreleaser release --clean --rm-dist
          else
            # Nightly release (use --snapshot for non-versioned release)
            goreleaser release --snapshot --clean --rm-dist
