name: Release

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 0 * * *'  # 每天0点触发
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Goreleaser Release (Snapshot)
        if: github.event_name != 'push' || startsWith(github.ref, 'refs/heads/') # 触发条件为手动或非 tag 的 push
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --rm-dist  # 快照发布
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Goreleaser Release (Official)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')  # 触发条件为 tag 的 push
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist  # 正式发布
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}